### ISSUE TITLE
snappi_tests: multidut support causes failures in single-dut runs

### ISSUE THREAD

**Issue by rraghav-cisco** [sonic-net/sonic-mgmt#12416]
@selldinesh , @isgmano , and @kamalsahu0001 

The multidut code is causing issues in single dut runs. The function generate_test_flows() has different arguments in definition and calls.
Definition:
<img width="1792" alt="Screenshot 2024-04-11 at 1 10 45 PM" src="https://github.com/sonic-net/sonic-mgmt/assets/58446052/4edf041f-939e-4928-a561-217caad25015">

Usage:
<img width="1792" alt="Screenshot 2024-04-11 at 1 13 47 PM" src="https://github.com/sonic-net/sonic-mgmt/assets/58446052/23334ad0-7dbf-4f83-9dd0-199332053154">

**Comment by kamalsahu0001** [comment]
Hi Raghav,

Seems you are having old version of multidut_helper.py file. Below is the latest code from sonic-mgmt. Please copy the latest file and run.

[A screenshot of a computer  Description automatically generated]

Regards,
Kamal.

From: rraghav-cisco ***@***.***>
Date: Thursday, April 11, 2024 at 1:14 PM
To: sonic-net/sonic-mgmt ***@***.***>
Cc: Kamal Sahu ***@***.***>, Mention ***@***.***>
Subject: [sonic-net/sonic-mgmt] snappi_tests: multidut support causes failures in single-dut runs (Issue #12416)
@selldinesh , @isgmano , and @kamalsahu0001 The multidut code is causing issues in single dut runs. The function generate_test_flows() has different arguments in definition and calls. Definition: Screenshot. 2024-04-11. at. 1. 10. 45. PM. png (view
ZjQcmQRYFpfptBannerStart
This Message is From an External Sender: Use caution opening files, clicking links or responding to requests.

ZjQcmQRYFpfptBannerEnd

@selldinesh<https://urldefense.com/v3/__https:/github.com/selldinesh__;!!I5pVk4LIGAfnvw!lS7agXzXvwR9e_21-Ee4mnMWL_qou8SsuEZIGopsk1eln4yk2ElsujYp0EWz2k5HC3OhS3-uHjQeX-f5XfC9tMQCi-Q$> , @isgmano<https://urldefense.com/v3/__https:/github.com/isgmano__;!!I5pVk4LIGAfnvw!lS7agXzXvwR9e_21-Ee4mnMWL_qou8SsuEZIGopsk1eln4yk2ElsujYp0EWz2k5HC3OhS3-uHjQeX-f5XfC9_R-CPbM$> , and @kamalsahu0001<https://urldefense.com/v3/__https:/github.com/kamalsahu0001__;!!I5pVk4LIGAfnvw!lS7agXzXvwR9e_21-Ee4mnMWL_qou8SsuEZIGopsk1eln4yk2ElsujYp0EWz2k5HC3OhS3-uHjQeX-f5XfC9CyhAc-A$>

The multidut code is causing issues in single dut runs. The function generate_test_flows() has different arguments in definition and calls.
Definition:
Screenshot.2024-04-11.at.1.10.45.PM.png (view on web)<https://urldefense.com/v3/__https:/github.com/sonic-net/sonic-mgmt/assets/58446052/4edf041f-939e-4928-a561-217caad25015__;!!I5pVk4LIGAfnvw!lS7agXzXvwR9e_21-Ee4mnMWL_qou8SsuEZIGopsk1eln4yk2ElsujYp0EWz2k5HC3OhS3-uHjQeX-f5XfC9rc3eAPw$>

Usage:
Screenshot.2024-04-11.at.1.13.47.PM.png (view on web)<https://urldefense.com/v3/__https:/github.com/sonic-net/sonic-mgmt/assets/58446052/23334ad0-7dbf-4f83-9dd0-199332053154__;!!I5pVk4LIGAfnvw!lS7agXzXvwR9e_21-Ee4mnMWL_qou8SsuEZIGopsk1eln4yk2ElsujYp0EWz2k5HC3OhS3-uHjQeX-f5XfC9VakaOxU$>

**Comment by rraghav-cisco** [comment]
@kamalsahu0001 , thanks for the response. I have pointed out that in 202311 itself - not my own workspace.

**Comment by kamalsahu0001** [comment]
Ok may be 202311 branch doesn’t have the code from master.

From: rraghav-cisco ***@***.***>
Date: Thursday, April 11, 2024 at 4:00 PM
To: sonic-net/sonic-mgmt ***@***.***>
Cc: Kamal Sahu ***@***.***>, Mention ***@***.***>
Subject: Re: [sonic-net/sonic-mgmt] snappi_tests: multidut support causes failures in single-dut runs (Issue #12416)
@kamalsahu0001 , thanks for the response. I have pointed out that in 202311 itself - not my own workspace. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: 
ZjQcmQRYFpfptBannerStart
This Message is From an External Sender: Use caution opening files, clicking links or responding to requests.

ZjQcmQRYFpfptBannerEnd

@kamalsahu0001<https://urldefense.com/v3/__https:/github.com/kamalsahu0001__;!!I5pVk4LIGAfnvw!kiHTnonVfAE2vvnphT8bSovlrH-27F1gurKq6H1-f_JNbFxQ9F-kyv8OtpEpS72Jd_9koYcYJjF1l4RS86bfGa4NF3Y$> , thanks for the response. I have pointed out that in 202311 itself - not my own workspace.

**Comment by rraghav-cisco** [comment]
@kamalsahu0001 : pls check.

**Comment by sdszhang** [comment]
@rraghav-cisco can you check if the issue still there?
