### ISSUE TITLE
[Test Gap] management ToR Routers should be tested with the MgmtToRRouter device type in minigraph

### ISSUE THREAD

**Issue by kellyyeh** [sonic-net/sonic-mgmt#5521]
**Description**
Test M0 devices with MgmtToRRouter in minigraph

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by Blueve** [comment]
@kellyyeh are you working on this test gap now?
If not, can I take this gap as this is a part of mgmt device qualification?
Rather than MgmtToRRouter, we need BmcMgmtToRRouter and MgmtTsToR(we already have this one now)

**Comment by Blueve** [comment]
Plan to add new topo `m0`
M0 is now a brand new role in network, it is partially act as a T0 and partially act as a T1.
It is not need to run all T0 test suite because M0 usually don't have too much overhead and no need some advanced feature like pfc/vxlan/everflow/...
It has some similarity with T1 because for some devices that don't have mgmt port, it will have BGP to collect devices' loopback to let user access them and manage them. And M0 can also have next layer (in-rack mgmt_switch, we called Mx), so it will also need to fwd DHCP Relay packet correctly just like T1.
