### ISSUE TITLE
[202205 xfail] test_auto_techsupport xfail for 202205 branch

### ISSUE THREAD

**Issue by StormLiangMS** [sonic-net/sonic-mgmt#6670]
**Description**
This issue is to track testWrArp failure for 202205 branch
show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_max_limit[core]:
show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_max_limit[techsupport]:
show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_rate_limit_interval:
show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_sanity:

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by StormLiangMS** [comment]
@lipxu  @xwjiang-ms from test result, looks like this one is fixed, could you close the issue and attached fixed PR here?

**Comment by lipxu** [comment]
@StormLiangMS I suppose the fix should be "https://github.com/sonic-net/sonic-mgmt/pull/6882", let me verify it before closing this issue, thanks.

**Comment by lipxu** [comment]
@StormLiangMS  Verified these cases locally on dualtor testbed, 
PR "https://github.com/sonic-net/sonic-mgmt/pull/6882" should be the key fix.
and for dualtor testbeds, should also include the PR "https://github.com/sonic-net/sonic-mgmt/pull/6918".

Since these cases could pass with these PRs, I will close the issue at this moment.
