### ISSUE TITLE
FDB test fails on BSL setups on key error

### ISSUE THREAD

**Issue by congh-nvidia** [sonic-net/sonic-mgmt#8730]
**Description**

**Steps to reproduce the issue:**
1. configure L2 on dut (https://github.com/Azure/SONiC/wiki/L2-Switch-mode)
2. run the fdb/test_fdb.py script on the dut

**Describe the results you received:**
```
duthosts = [<MultiAsicSonicHost arc-switch1004>]
rand_one_dut_hostname = 'arc-switch1004'
tbinfo = {'comment': 'Mellanox MTR testbed', 'conf-name': 'arc-switch1004-t0', 'duts': ['arc-switch1004'], 'duts_map': {'arc-switch1004': 0}, ...}

    @pytest.fixture(scope="module")
    def utils_vlan_intfs_dict_orig(duthosts, rand_one_dut_hostname, tbinfo):
        '''A module level fixture to record duthost's original vlan info
    
        Args:
            duthosts: All DUTs belong to the testbed.
            rand_one_dut_hostname: hostname of a random chosen dut to run test.
            tbinfo: A fixture to gather information about the testbed.
    
        Returns:
            VLAN info dict with original VLAN info
            Example:
                "Vlan1000": {
                    "fc02:1000::1/64": {},
                    "grat_arp": "enabled",
                    "proxy_arp": "enabled",
                    "192.168.0.1/21": {}
                }
        '''
        duthost = duthosts[rand_one_dut_hostname]
        cfg_facts = duthost.config_facts(host=duthost.hostname, source="persistent")['ansible_facts']
        vlan_intfs_dict = {}
        for k, v in list(cfg_facts['VLAN'].items()):
            vlanid = v['vlanid']
>           for addr in cfg_facts['VLAN_INTERFACE']['Vlan'+vlanid]:
E           KeyError: 'VLAN_INTERFACE'

cfg_facts  = {'AUTO_TECHSUPPORT': {'GLOBAL': {'available_mem_threshold': '10.0', 'max_core_limit': '5.0', 'max_techsupport_limit': ...'Ethernet100': {'brkout_mode': '1x100G[50G,40G,25G,10G]'}, 'Ethernet104': {'brkout_mode': '2x50G[25G,10G]'}, ...}, ...}
duthost    = <MultiAsicSonicHost arc-switch1004>
duthosts   = [<MultiAsicSonicHost arc-switch1004>]
k          = 'Vlan1000'
rand_one_dut_hostname = 'arc-switch1004'
tbinfo     = {'comment': 'Mellanox MTR testbed', 'conf-name': 'arc-switch1004-t0', 'duts': ['arc-switch1004'], 'duts_map': {'arc-switch1004': 0}, ...}
v          = {'vlanid': '1000'}
vlan_intfs_dict = {}
vlanid     = '1000'

common/fixtures/duthost_utils.py:359: KeyError
```
This issue is similar to https://github.com/sonic-net/sonic-mgmt/issues/4742.

**Describe the results you expected:**
The test should not have any tests issues when running on BSL setups.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by qiluo-msft** [comment]
Is it on a specific or newer HwSKU or general for all HwSKU of one vendor?

**Comment by bpar9** [comment]
> Is it on a specific HwSKU, or a general issue for all HwSKU of one vendor?

We see this with other HWSKU of other vendors also. On additional debugging, here is the analysis on this issue:

- We analyzed that the problem is happening in BSL setup stage when we try to convert the system to L2 mode using
./testbed-cli.sh set-l2 ${{ parameters.TESTBED_NAME }} password.txt
 
- above utility gets the L2 related config on DUT using below command – “sonic-cfggen -H -k {{ hwsku }} -p --preset l2 > /tmp/init_l2_config.json”
  Complete flow of the script is located at
https://github.com/sonic-net/sonic-mgmt/blob/master/ansible/testbed_set_l2_mode.yml
 
- after the above utility is run, we observed that the following config is missing in the converted config_db.json
 
"VLAN_INTERFACE": {
        "Vlan1000|192.168.0.1/21": {}, 
        "Vlan1000": {}, 
        "Vlan1000|fc02:1000::1/64": {}
    },
 
- we went ahead and separately updated this config and we no longer see the KEY error and we are able to proceed further in the script execution
- on further analysis we see that the above script utilizes the following template to generate the L2 config
 https://github.com/sonic-net/sonic-buildimage/blob/master/src/sonic-config-engine/data/l2switch.j2
 
and this file is missing the VLAN_INTERFACE section. All copies of l2switch.j2 on the system are missing this section.
