### ISSUE TITLE
[cacl] [chassis] acl table output needs new parsing method for chassis

### ISSUE THREAD

**Issue by wenyiz2021** [sonic-net/sonic-mgmt#9864]
**Description**
output of `show acl table` for chassis has 6 columns, iso 4/5.
the following parsing of output code needs to be enhanced for chassis

https://github.com/sonic-net/sonic-mgmt/blob/c1f8c80af3416476e140087e89576f8d7d495c01/tests/cacl/test_cacl_application.py#L258

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rawal01** [comment]
In def get_cacl_tables_and_rules,  the ouput is split based on space but this not accurate because within field values
 for line in stdout_lines:
            tokens = line.strip().split()
            if len(tokens) == 7 and tokens[0] == table["name"]:
 This does not work as shown in example below from chassis:
show acl table NTP_ACL
Table                             Rule                             Priority    Action    Match                        Status
-------                          ------                           ----------  --------  -------                          --------
NTP_ACL                     NTP_ACL  RULE_1         9999        DROP      SRC_IP: 20.0.0.2/32   {'asic0': 'N/A', 'asic1': 'N/A'}"

some of the fields have space in values like SRC_IP: 20.0.0.2/32 and also in status so for it gets tokens = 10 and fails length check. Similarly, for single asic pizza box it will be 6 and for supervisor we get 7 so this mechanism will not work for different platform types. 

We need to come up with new mechanism to parse this output.
